add(automation): build webhooks with a matrix
indentapis/integrations pull request #29
Opened 2022-06-03 16:33 UTC by kodjoz

2022-06-13 19:04 UTC, ethernetdan requested changes
Probably want to separate variables and outputs from `main.tf`

2022-06-13 19:04 UTC, ethernetdan commented on utils/scripts/js/writeTerraform.ts
> +  })
Write to `variables.tf`

2022-06-13 19:04 UTC, ethernetdan commented on utils/scripts/js/writeTerraform.ts
> +  })
Write to `outputs.tf`

2022-06-14 16:08 UTC, fouad approved these changes

2022-06-14 16:08 UTC, merged